goal = num_items(Part.RAM) + 100
while num_items(Part.RAM) < goal:
    harvest()
    move(North)
    harvest()
    move(North)
    harvest()
    move(East)
    harvest()
    move(South)
    harvest()
    move(South)
    harvest()
    move(East)
    harvest()
    move(North)
    harvest()
    move(North)
    harvest()
    move(West)
    move(West)
    move(South)
    move(South)
